// =============================================================================
// 1. INCLUDES & GLOBAL DEFINITIONS
// =============================================================================
// stdlib
#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
// system
#include <fcntl.h>
#include <poll.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/ip.h>
// C++
#include <string>
#include <vector>
// proj
#include "hashtable.h"

#define container_of(ptr, T, member) \
    ((T *)( (char *)ptr - offsetof(T, member) ))

const size_t k_max_msg = 32 << 20; //max message size?
const size_t k_max_args = 200 * 1000;

enum {
    RES_OK = 0,
    RES_ERR = 1,
    RES_NX = 2,
};

// =============================================================================
// 2. DATA STRUCTURES
// =============================================================================

struct Conn{
    int fd = -1;
    bool want_read = false; //represetns fd list for readiness API
    bool want_write = false; 
    bool want_close = false; //tells even loop to destroy the connection

    std::vector<uint8_t> incoming; //data to be parsed by the application 
    std::vector<uint8_t> outgoing; //responses generated by the application 
};

//internal format for a reply,
struct Response{
    uint32_t status = 0; //returns the status in integer -> maps to differnet meanings
    std::vector<uint8_t> data; //holds teh actual value in raw byte format
};

//global variable that stores the database
//main hash table that stores all keys and values
static struct {
    HMap db;    // top-level hashtable
} g_data;

// KV pair for the top-level hashtable
// represetns one redis key value pair
//Example: 
    //SET name "alice"
    //node 
    //key = "name"
    //val = "alice"
struct Entry {
    struct HNode node;  // hashtable node
    std::string key;
    std::string val;
};


// =============================================================================
// 3. PRIMITIVE HELPERS (Byte Manipulation)
// =============================================================================
static void msg(const char *msg) {
    fprintf(stderr, "%s\n", msg);
}

static void msg_errno(const char *msg) {
    fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void buf_append(std::vector<uint8_t> &buf, const uint8_t *data, size_t len){
    buf.insert(buf.end(), data, data + len); //adds at the end of the buffer
}
//remove from the front, remove n bytes
static void buf_consume(std::vector<uint8_t> &buf , size_t n){
    buf.erase(buf.begin(), buf.begin()+n);

}
static bool read_str(const uint8_t *&cur, const uint8_t *end, size_t n, std::string &out){
    if (cur + n > end){ //boundary check, cur is current poisition, end is cliff edge of valid data -> prevents a buffer over read
        return false;
    }
    out.assign((const char*)cur, n); //extracts starting at the cur address and the ending addressa and copies bytes into std::string in internal memory
    cur += n; //advance hte cursor
    return true;
}
static bool read_u32(const uint8_t *&cur, const uint8_t *end, uint32_t &out) { // safely extract 32 bit integer from byte in buffer
    if(cur + 4 > end){ //boundary check, cur is current poisition, end is cliff edge of valid data -> prevents a buffer over read
        return false;
    }

    memcpy(&out, cur, 4); //takes 4 raw bytes starting at the addrtess of cur and copies directly to memory address of out. 
    cur += 4;
    return true;

}
static bool entry_eq(HNode *lhs, HNode *rhs) {
    struct Entry *le = container_of(lhs, struct Entry, node); //lhs pointer to the node. container find teh entry struct that contains the node
    struct Entry *re = container_of(rhs, struct Entry, node); //rhs " " 
    return le->key == re->key; //returns true or false based on whether the keys are the same
}
// =============================================================================
// 4. PROTOCOL LAYER (Parsing & Serialization)
// =============================================================================

static int32_t parse_req(const uint8_t *data, size_t size, std::vector<std::string> &out) {
    const uint8_t *end = data + size; //pointer to end of request message?

    uint32_t nstr = 0; //index of the message
    if(!read_u32(data, end, nstr)){ //if data is too short fails
        return -1;
    }

    if(nstr > k_max_args){
        return -1; //too long fails
    }

    while(out.size() < nstr){
        uint32_t len = 0;
        if(!read_u32(data, end, len)){ // read the string length, returns the length with integer value and places it in len 
            return -1; 
        }
        out.push_back(std::string()); //convert to string 
        if (!read_str(data, end, len, out.back())) { //read actual string
            return -1;
        }
    }
    if(data != end){
        return -1; //trailing garbage
    }
    return 0;

}

static void make_response(const Response &resp, std::vector<uint8_t> &out) {
    uint32_t resp_len = 4 + (uint32_t)resp.data.size();
    buf_append(out, (const uint8_t *)&resp_len, 4);
    buf_append(out, (const uint8_t *)&resp.status, 4);
    buf_append(out, resp.data.data(), resp.data.size());
}

static uint64_t str_hash(const uint8_t *data, size_t len) {
    uint32_t h = 0x811C9DC5;
    for (size_t i = 0; i < len; i++) {
        h = (h + data[i]) * 0x01000193;
    }
    return h;
}


// =============================================================================
// 5. APPLICATION LAYER (KV Store Logic)
// =============================================================================

static void do_get(std::vector<std::string> &cmd, Response &out){

    Entry key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());

    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if(!node){
        out.status = RES_NX;
        return;
    }

    const std::string &val = container_of(node, Entry, node)->val ;
    assert(val.size() <= k_max_msg);
    out.data.assign(val.begin(), val.end());

}

static void do_set(std::vector<std::string> &cmd, Response &out){
    Entry key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);

    if(node){
        container_of(node, Entry, node)->val.swap(cmd[2]);
        out.status = RES_OK;
    }
    else{
        Entry *ent = new Entry();
        ent->key.swap(key.key);
        ent->node.hcode = key.node.hcode;
        ent->val.swap(cmd[2]);
        hm_insert(&g_data.db, &ent->node);
    }

    out.status = RES_OK;
}


static void do_del(std::vector<std::string> &cmd, Response &out){
    Entry key; 
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    HNode *node = hm_delete(&g_data.db, &key.node, &entry_eq);
    if(node){
        delete container_of(node, Entry,node);
        out.status = RES_OK;

    }
    else{
        out.status = RES_NX;
    }
}
static void do_request(std::vector<std::string> &cmd, Response &out) {
    if (cmd.size() == 2 && cmd[0] == "get") {
        return do_get(cmd, out);
    } else if (cmd.size() == 3 && cmd[0] == "set") {
        return do_set(cmd, out);
    } else if (cmd.size() == 2 && cmd[0] == "del") {
        return do_del(cmd, out);
    } else {
        out.status = RES_ERR;
    }
}



// =============================================================================
// 6. NETWORK LAYER (Socket Handlers & Event Loop)
// =============================================================================


static void fd_set_nb(int fd){
    int flags = fcntl(fd, F_GETFL, 0);
    if(flags < 0){
        die("fcntl");
    }

    flags |= O_NONBLOCK;

    if(fcntl(fd, F_SETFL, flags) < 0){
        die("fcntl");
    }
}

static bool try_one_request(Conn *conn){
    if (conn->incoming.size() < 4){
        return false;
    }

    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);

    if(len > k_max_msg){
        msg("too long");
        conn->want_close = true;
        return false;
    }

    if( 4 + len > conn->incoming.size()){
        return false;
    }

    const uint8_t *request = &conn->incoming[4];

    std::vector<std::string> cmd;
    if (parse_req(request, len, cmd) < 0) {
        msg("bad request");
        conn->want_close = true;
        return false;
    }

    Response resp;
    do_request(cmd, resp);
    make_response(resp, conn->outgoing);

    buf_consume(conn->incoming, 4 + len);
    return true;   
}

static Conn *handle_accept(int fd){

    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);

    if (connfd < 0){
        msg_errno("accept() error");
        return NULL;
    }

    fd_set_nb(connfd);

    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true;

    return conn;

}

static void handle_write(Conn *conn);

static void handle_read(Conn *conn){
    uint8_t buf[64*1024];
    ssize_t rv = read(conn->fd, buf, sizeof(buf));

    if (rv < 0 && errno == EAGAIN) return;

    if (rv < 0){
        msg_errno("read() error");
        conn->want_close = true;
        return;
    }

    if (rv == 0){
        if (conn->incoming.size() == 0){
            msg("client closed");
        } else{
            msg("unexpected EOF");
        }
        conn->want_close = true;
        return;
    }

    buf_append(conn->incoming, buf, (size_t)rv);

    while (try_one_request(conn)) {}

    if (conn->outgoing.size() > 0) {
        conn->want_read = false;
        conn->want_write = true;
        handle_write(conn);
    }
}

static void handle_write(Conn *conn){
    assert(conn->outgoing.size() >0);

    ssize_t rv = write(conn->fd, conn->outgoing.data(), conn->outgoing.size());

    if (rv < 0 && errno == EAGAIN){
        return;
    }

    if (rv < 0){
        msg_errno("write() error");
        conn->want_close = true;
        return;
    }

    buf_consume(conn->outgoing, (size_t)rv);

    if (conn->outgoing.size() == 0){
        conn->want_read = true;
        conn->want_write = false;
    }
}

void die(const char* msg) {
    perror(msg);
    exit(1);
}


int main(){

    int fd = socket(AF_INET, SOCK_STREAM, 0);

    int val = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

    struct sockaddr_in addr = {};
    addr.sin_family = AF_INET;
    addr.sin_port = htons(1234);
    addr.sin_addr.s_addr = htonl(0);

    int rv = bind(fd, (const struct sockaddr *)&addr, sizeof(addr));
    if (rv) { die("bind()"); }

    fd_set_nb(fd);

    rv = listen(fd, SOMAXCONN);
    if (rv) {die("listen()");};

    std::vector<Conn *> fd2conn;
    std::vector<struct pollfd> poll_args;

    while (true) {

        poll_args.clear();

        struct pollfd pfd = {
            fd,
            POLLIN,
            0
        };

        poll_args.push_back(pfd);

        for (Conn *conn : fd2conn) {

            if (!conn) {
                continue;
            }

            struct pollfd pfd = {
                conn->fd,
                POLLERR,
                0
            };

            if (conn->want_read) {
                pfd.events |= POLLIN;
            }

            if (conn->want_write) {
                pfd.events |= POLLOUT;
            }

            poll_args.push_back(pfd);
        }

        int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), -1);

        if(rv < 0 && errno == EINTR){
            continue;
        }

        if (rv < 0){
            die("poll");
        }  

        if (poll_args[0].revents){
            Conn *conn = handle_accept(fd);

            if (conn){
                if (fd2conn.size() <= (size_t)conn->fd){
                    fd2conn.resize(conn->fd + 1);
                }

                fd2conn[conn->fd] = conn;
            }
        }

        for (size_t i = 1; i < poll_args.size(); ++i){

            uint32_t ready = poll_args[i].revents;

            if (ready == 0){
                continue;
            }

            Conn *conn = fd2conn[poll_args[i].fd];

            if (ready & POLLIN){
                handle_read(conn);
            }

            if (ready & POLLOUT && !conn->want_close){
                handle_write(conn);
            }

            if (ready & POLLERR || conn->want_close){
                (void)close(conn->fd);
                fd2conn[conn->fd] = NULL;
                delete conn;
            }
        }
    }
}