#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/ip.h>
#include <cassert>
#include <vector>
#include <poll.h>
#include <fcntl.h>



//structs already defined in headers, here for understanding what is in them and the different varaiables. 
/*
struct sockaddr_in {
    uint16_t sin_family;
    uint16_t sin_port;
    struct in_addr sin_addr;
};

struct in_addr{
    uint32_t s_addr;
};
*/
//holds an IPv4:port pair stored as big-endian numbers converted by htons() and htonl()
//1.2.3.4 is represented by htonl(0x01020304)
//more explanation about htonl and htons -=> not neded follow the below for abstraction

struct Conn{
    int fd = -1;
    bool want_read = false; //represetns fd list for readiness API
    bool want_write = false; 
    bool want_close = false; //tells even loop to destroy the connection

    std::vector<uint8_t> incoming; //data to be parsed by the application 
    std::vector<uint8_t> outgoing; //responses generated by the application 
};
static void buf_append(std::vector<uint8_t> &buf, const uint8_t *data, size_t len){
    buf.insert(buf.end(), data, data + len); //adds at the end of the buffer
}
//remove from the front, remove n bytes
static void buf_consume(std::vector<uint8_t> &buf , size_t n){
    buf.erase(buf.begin(), buf.begin()+n);

}

static void msg(const char *msg) {
    fprintf(stderr, "%s\n", msg);
}

void die(const char* msg) {
    perror(msg);
    exit(1);
}
const size_t k_max_msg = 4096; //max message size?

//reads now nonblocking so not needed but good to have
//blocking helpers not used right now 
static int32_t read_full(int fd, char *buf, size_t n ){
    while (n>0){
        ssize_t rv = read(fd, buf, n);
        if(rv <= 0){
            return -1;
        }
        assert((size_t)rv <= n );
        n -= (size_t)rv;
        buf += rv;
        
    }
    return 0;
}
static int32_t write_all(int fd, char *buf, size_t n){
    while (n >0){
        ssize_t rv = write(fd, buf, n );

    
     assert((size_t)rv <= n );
        n -= (size_t)rv;
        buf += rv;
        
    }
    return 0;
}
// read and write to the connected socket handle
// unused because uses blocking read and write
static int32_t one_request(int connfd){
    //4 butes header
    char rbuf[4+k_max_msg]; //actual content ignoring the buffer
    errno = 0;
    int32_t err = read_full(connfd, rbuf, 4);

    if(err){
        msg(errno == 0 ? "EOF": "read() error");
        return err;
    }

    uint32_t len = 0;
    memcpy(&len, rbuf, 4); //extracts length of the message, number of bytes of payload to read next
    if (len > k_max_msg){
        msg("too long");
        return -1;
    }

    //request body
    err = read_full(connfd, &rbuf[4], len);
    if(err){
        msg("read() error");
        return err; 
    }
    //do something 
    printf("client says: %.*s\n", len, &rbuf[4]);
    // reply using the same protocol
    const char reply[] = "world";
    char wbuf[4 + sizeof(reply)];
    len = (uint32_t)strlen(reply);
    memcpy(wbuf, &len, 4);
    memcpy(&wbuf[4], reply, len);
    return write_all(connfd, wbuf, 4 + len);
}
//read and write 


static void fd_set_nb(int fd){
    fcntl(fd, F_SETFL, fcntl(fd, F_GETFL, 0) | O_NONBLOCK); // make the listening scoket non blocking

    //non blocking means check if something happened, otehrwise keep going, do not wait until something happens
    //allows for multiple threads to be active. 
}
//process 1 request if there is enough data
static bool try_one_request(Conn *conn){
    if (conn->incoming.size() < 4){//message is at least 4 bytes long with the length header, if less than 4 then its not done recieving the bytes
        return false; //want read
    }

    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);//returns length of the message to len, recieves incoming data
    if(len > k_max_msg){
        conn->want_close = true;
        return false; //want close
    }

    if( 4 + len > conn->incoming.size()){//length of the message and size of the message do not match up 
        return false; //want read
    }

    //building response
    const uint8_t *request = &conn->incoming[4]; //pointer to the fist byter buffer of the message body
    //process the repsonse 
    printf("client says: len:%d data:%.*s\n",
        len, len < 100 ? len : 100, request);

    buf_append(conn->outgoing, (const uint8_t *)&len, 4); // append 4 bytes (header) to the outgoing buffer, 
    buf_append(conn->outgoing, request, len); //append the message body of the outgoing buffer
    // 5. Remove the message from `Conn::incoming`.
    buf_consume(conn->incoming, 4 + len); //remove the message and header from the incoming buffer
    return true;
}

static Conn *handle_accept(int fd){
    //accept
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);
    if (connfd < 0){
        return NULL;
    }

    //set new connection fd to non blocking mode
    fd_set_nb(connfd);

    //create a Conn struct
    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true;
    //no conn want_write because buffer is empty
    return conn;

}
static void handle_write(Conn *conn);
static void handle_read(Conn *conn){
    uint8_t buf[64*1024]; //nonblocking read
    ssize_t rv = read(conn->fd, buf, sizeof(buf));
    if (rv < 0 && errno == EAGAIN){
        return; //socket not actually ready
    }

    
    if (rv <= 0){
        conn->want_close = true;
        return;
    }
    //add new data to the buffer
    buf_append(conn->incoming, buf, (size_t)rv);
    while (try_one_request(conn)) {}
    // update readiness intention
    if (conn->outgoing.size() > 0) {    // has a response
        conn->want_read = false;
        conn->want_write = true;
        handle_write(conn);
    }   // else: want read
    
}

static void handle_write(Conn *conn){
    assert(conn->outgoing.size() >0);
    ssize_t rv = write(conn->fd, conn->outgoing.data(), conn->outgoing.size()); //writing data and size to fd (socket handle)
    if (rv < 0 && errno == EAGAIN){
        return;
    }
    if (rv < 0){
        conn->want_close = true; //error handling no more bytes to write into
        return;
    }
    buf_consume(conn->outgoing, (size_t)rv);
    // update the readiness intention
    if (conn->outgoing.size() == 0) {   // all data written
        conn->want_read = true;
        conn->want_write = false;
    } // else: want write
}
//append to the back 
//args: buffer, pointer to 


int main(){
    //socket handle
    int fd = socket(AF_INET, SOCK_STREAM, 0); //AF_INET is from IPv4, inet6 for IPV6, sock strem is for TCP

    //set socket options
    //2nd and 3rd arugments specifies which option to set
    //4th arg option value ie: 1
    //always set SO_REUSEADDR to be 1 or it wont be able to bind to same IP:port after a restart, keep convention for all listening ports
    int val = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

    //bind to an address 0.0.0.0:1234 
    struct sockaddr_in addr = {};
    addr.sin_family = AF_INET;
    addr.sin_port = htons(1234); //port
    addr.sin_addr.s_addr = htonl(0); //wildcard IP 0.0.0.0
    int rv = bind(fd, (const struct sockaddr *)&addr, sizeof(addr));

    if (rv) { die("bind()"); }

    fd_set_nb(fd); //set listening socket to non blocking

 
    //listen 
    rv = listen(fd, SOMAXCONN); //SOMAXCONN is 4096 on linux
    if (rv) {die("listen()");};


    /* CONSTRUCT THE EVNET LOOP*/
    //fd is the listening socket
    // essentially a hashmap of all connections as the value for the fd key
    std::vector<Conn *> fd2conn; //map of all client connection keyed by fd

    //poll is Linux API, takes a list of fd that program wants IO on, returns a list of fds that are ready for IO 


    //event loop
    std::vector<struct pollfd> poll_args;
    while (true) {
    // --------------------------------------------------
    // STEP 1: Build the list of sockets to monitor
    // --------------------------------------------------
    // poll() does NOT know about your connections.
    // You must give it a list every iteration.
    // So we rebuild the list each loop.
    poll_args.clear();

    // --------------------------------------------------
    // STEP 1A: Add the listening socket
    // --------------------------------------------------
    // Why first?
    // Because index 0 is reserved for accepting new clients.
    // We want poll() to notify us when:
    // "A new client is trying to connect"
    struct pollfd pfd = {
        fd,        // socket to monitor
        POLLIN,    // we want to know when it is readable
        0          // OS writes readiness result here
    };

    poll_args.push_back(pfd);

    // --------------------------------------------------
    // STEP 1B: Add all existing client connections
    // --------------------------------------------------
    // fd2conn maps fd → Conn object.
    // Each Conn tells us what it wants:
    // - read more data?
    // - write pending response?
    for (Conn *conn : fd2conn) {

        // Skip empty slots in the fd map
        if (!conn) {
            continue;
        }

        // We ALWAYS monitor errors
        // because a broken socket must be closed.
        struct pollfd pfd = {
            conn->fd,   // client's socket
            POLLERR,    // always check errors
            0
        };

        // If application wants to READ from socket
        if (conn->want_read) {
            pfd.events |= POLLIN;
        }

        // If application has data to WRITE
        if (conn->want_write) {
            pfd.events |= POLLOUT;
        }

        // Add this socket to the OS watch list
        poll_args.push_back(pfd);
    }

    // After this point:
    // poll_args contains ALL sockets the server cares about.
    

        //wait for readiness   
        //poll can return when at least one of the fds are ready
        //OR when err = EINTR, allows process a chance to handle the signal 
        int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), -1);
        if(rv < 0 && errno == EINTR){
            continue;
        }
        if (rv < 0){
            die("poll");
        }  

        //Invoke Application Callbacks
        //accept treated as readiness notification -> POLLIN
        //poll returns and check the 1st fd if we can accept
        if (poll_args[0].revents & POLLIN){
            Conn *conn = handle_accept(fd);
            if (conn){
                if (fd2conn.size() <= (size_t)conn->fd){
                    fd2conn.resize(conn->fd + 1);
                }
                fd2conn[conn->fd] = conn;
            }
        }

        for (size_t i = 1; i < poll_args.size(); ++i){ //skip first poll argument 
            uint32_t ready = poll_args[i].revents;// copies readiness flags returned by OS, revents is a bitmask that continas multiple flags
            Conn *conn = fd2conn[poll_args[i].fd]; //finds the connection state object for that socket, given socket number find the state of the client
            if (ready & POLLIN){
                handle_read(conn); // read since POLLIN is true
            }
            if (ready & POLLOUT){
                handle_write(conn); //write since POLLOUT is true

            }
            //terminate connections, destroy connect with error or if request want_close
            // close the socket from socket error or applicatoin logic
            if (ready & POLLERR || conn->want_close){
                (void)close(conn->fd);
                fd2conn[conn->fd] = NULL;
                delete conn;
            }
        }
    }

    
}

